gh-16 Data Input screen was added
MAVIKE/yad-flutter pull request #32
Opened 2021-05-01 14:34 UTC by ilyalevushkin

closes #16.
Старался делать все по фигме.
При нажатии на кнопку Pay происходит проверка введенных данных и дальше стоит заглушка.

Реализовал сам виджет карточки в widgets/. Экран же создал в папке screens/ и оттуда уже вызывал свой виджет.

![image](https://user-images.githubusercontent.com/36894819/116785623-46412e00-aaa3-11eb-8a57-c1943a21a226.png)
![image](https://user-images.githubusercontent.com/36894819/116785626-493c1e80-aaa3-11eb-8ae3-63e905c16a82.png)

2021-05-02 08:27 UTC, Ksupall approved these changes

2021-05-02 11:47 UTC, RyazMax approved these changes

2021-05-02 19:38 UTC, vovac12 commented on lib/widgets/data_input_card.dart
> +  Widget build(BuildContext context) {
Лучше создать отдельный виджет для поля ввода. Чтобы не было повторяющегося кода

2021-05-02 19:38 UTC, vovac12 commented on lib/widgets/data_input_card.dart
> +class _CardData {
Посмотри как у меня реализовано в PR #34. Bloc + Formz облегчит валидацию и работу с внешними ресурсами.

2021-05-02 19:38 UTC, vovac12 commented on lib/widgets/data_input_card.dart
> +  void setCardNumber(String cardNumber) {
В dart принято использовать сеттеры в таких ситуациях.
```
set cardNumber(String cadNumber) => _cardNumber = cardNumber;
```

2021-05-02 19:38 UTC, vovac12 commented on lib/widgets/data_input_card.dart
> +  bool isCardNumberCorrect() {
Тут можно использовать геттер
```
bool get isCardNumberCorrect => (...);
```

2021-05-02 19:38 UTC, vovac12 commented on lib/widgets/data_input_card.dart
> +  String? getCardNumber() {
Тоже самое. Используем геттеры.

2021-05-02 19:43 UTC, vovac12 commented on lib/screens/payment_screen.dart
> +  PaymentScreen(): _lightTheme = LightTheme();
Используем `context.read<ITheme>()` для получения темы в методе `build`.

2021-05-04 15:44 UTC, ilyalevushkin commented on lib/screens/payment_screen.dart
> +  PaymentScreen(): _lightTheme = LightTheme();
поправил

2021-05-04 15:44 UTC, ilyalevushkin commented on lib/widgets/data_input_card.dart
> +  String? getCardNumber() {
убрал это

2021-05-04 15:44 UTC, ilyalevushkin commented on lib/widgets/data_input_card.dart
> +  bool isCardNumberCorrect() {
убрал это

2021-05-04 15:44 UTC, ilyalevushkin commented on lib/widgets/data_input_card.dart
> +  void setCardNumber(String cardNumber) {
убрал это

2021-05-04 15:45 UTC, ilyalevushkin commented on lib/widgets/data_input_card.dart
> +class _CardData {
Посмотрел. Сделал также как у тебя. Так удобней

2021-05-04 15:45 UTC, ilyalevushkin commented on lib/widgets/data_input_card.dart
> +  Widget build(BuildContext context) {
Сделал виджеты для полей вода и кнопки

2021-05-04 16:53 UTC, vovac12 requested changes
В целом всё классно 👍.

2021-05-04 16:53 UTC, vovac12 commented on lib/features/payment/view/payment_form.dart
> +        height: context.read<ITheme>().dataInputCardTheme.cardHeight,
Можно перед `return`ом один раз получить тему и использовать её. Всё же чтение темы из контекста не бесплатная операция.

2021-05-04 16:53 UTC, vovac12 commented on lib/main.dart
>  class MyApp extends StatelessWidget {
Кажется этот класс больше не нужен

2021-05-04 19:23 UTC, ilyalevushkin commented on lib/features/payment/view/payment_form.dart
> +        height: context.read<ITheme>().dataInputCardTheme.cardHeight,
поправил
https://github.com/MAVIKE/yad-flutter/pull/32/commits/701159bd839b63a0afe4ae87e3484a25136e6c7b

2021-05-04 19:26 UTC, ilyalevushkin commented on lib/main.dart
>  class MyApp extends StatelessWidget {
Пардон, забыл удалить. Исправил:
30819cc

2021-05-04 19:31 UTC, vovac12 approved these changes

2021-05-04 19:41 UTC, merged