Fb 20 dish list screen
MAVIKE/yad-flutter pull request #36
Opened 2021-05-06 07:34 UTC by ilyalevushkin

Closes #20.
Примеры работы программы:
![image](https://user-images.githubusercontent.com/36894819/117258211-64b57980-ae55-11eb-85a7-4dcfad86073f.png)
![image](https://user-images.githubusercontent.com/36894819/117258229-6a12c400-ae55-11eb-829a-3c5572a2ed21.png)
![image](https://user-images.githubusercontent.com/36894819/117258290-772fb300-ae55-11eb-8e96-befc4fd7f513.png)

Добавил UserDishListRepository репозиторий, который будет обращаться к api-client. В нем стоит заглушка, которая возвращает тестовые данные.

Отображение данных работает весьма примитивно: при загрузки страницы, делается запрос категорий соответствующего ресторана, а также делается запрос списка блюд первой категории (чтобы в самом начале что-нибудь отобразить).
При нажатии на кнопку категории (Пицца, Бургеры, Wok,...) делается запрос списка блюд соответсвующей категории.

Можно было бы, конечно, хранить для каждой категории список блюд и при повторном нажатии на категорию не идти на сервер за данными, но думаю, для начала и так сойдет.

2021-05-06 16:42 UTC, Ksupall approved these changes

2021-05-06 16:50 UTC, vovac12 requested changes

2021-05-06 16:50 UTC, vovac12 commented on lib/core/domain/repos/load_dish_list/user_dish_list_repo.dart
> +  // заполнял всякой ерундой, чтоб посмотреть, как выглядеть будет
Можно было сделать MockDishListRepository. И приставка User не обязательна, у курьра не будет своего меню. Можно использовать RemoteDishListRepository, что на ряду с MockDishListRepository будет выглядеть адекватно.

2021-05-06 16:50 UTC, vovac12 commented on lib/features/dish_list/bloc/dish_list_event.dart
> +class CategoryListFetched extends DishListEvent {}
Эвенты это события, которые мы получаем от UI и других BLoC'ов. И они не могут знать о том, что категории или блюда были получены. Это моя ошибка, что наплодил кучу эвентов в своем PR, сейчас вроде поправил

2021-05-06 16:50 UTC, vovac12 commented on lib/features/dish_list/bloc/dish_list_bloc.dart
> +  // делается запрос на получение списка блюд первой категории
Можно возвращать Stream из этой функции и использовать несколько раз yield (после получения категорий и после получения блюд)

2021-05-06 16:50 UTC, vovac12 commented on lib/features/dish_list/view/category_scroll_list.dart
> +class _CategoryScrollListState extends State<CategoryScrollList> {
Какое состояние у этого виджета?

2021-05-06 16:50 UTC, vovac12 commented on lib/features/dish_list/view/dish_list_page.dart
> +        )
Это выглядит немного странно. Лучше добавлять первое событие в конструкторе

2021-05-06 16:50 UTC, vovac12 commented on lib/features/dish_list/widgets/dish_category.dart
> +                    DishListFetched(_categoryId)
DishListCategoryChanged?

2021-05-07 12:36 UTC, ilyalevushkin commented on lib/features/dish_list/bloc/dish_list_event.dart
> +class CategoryListFetched extends DishListEvent {}
Да, я это понял, просто назвал по-тупому. Изменил: https://github.com/MAVIKE/yad-flutter/pull/36/commits/3f6040efebd38ccbcfb87c05728bea921a45d249
CategoryListFetched -> CategoryListRequested (запрос списка категорий)
DishListFetched -> DishListRequestedByCategoryId(запрос списка блюд по id категории)

2021-05-07 12:37 UTC, ilyalevushkin commented on lib/features/dish_list/widgets/dish_category.dart
> +                    DishListFetched(_categoryId)
Ну типа да. Я назвал DishListRequestedByCategoryId. То есть запрошен список блюд по соответствующему id категории: https://github.com/MAVIKE/yad-flutter/pull/36/commits/3f6040efebd38ccbcfb87c05728bea921a45d249
Пойдет?

2021-05-07 12:46 UTC, ilyalevushkin commented on lib/core/domain/repos/load_dish_list/user_dish_list_repo.dart
> +  // заполнял всякой ерундой, чтоб посмотреть, как выглядеть будет
Согласен. Изменил: https://github.com/MAVIKE/yad-flutter/pull/36/commits/b0fa4aadedaddf230c4a7490bee83f67eb3f8636
Создал заглушку RemoteDishListRepository и переименовал UserDishListRepository в MockDishListRepository.

2021-05-07 13:02 UTC, ilyalevushkin commented on lib/features/dish_list/view/category_scroll_list.dart
> +class _CategoryScrollListState extends State<CategoryScrollList> {
Никакого, нету тут состояния. Я просто изначально делал по примеру с бесконечным scroll list: https://bloclibrary.dev/#/flutterinfinitelisttutorial
И там состояние было (при прокрутке до самого низа, вызывалось событие, которое дозапрашивает данные с сервера).
Убрал:  https://github.com/MAVIKE/yad-flutter/pull/36/commits/2dccb1a665bc00126bd3fd6bdf71b4f187022e6d

2021-05-07 13:09 UTC, ilyalevushkin commented on lib/features/dish_list/view/dish_list_page.dart
> +        )
Да, согласен.
Исправил: https://github.com/MAVIKE/yad-flutter/pull/36/commits/bb2297e9fb4dd4e835e66d59a49331bd9f9bfa1e

2021-05-07 16:56 UTC, ilyalevushkin commented on lib/features/dish_list/bloc/dish_list_bloc.dart
> +  // делается запрос на получение списка блюд первой категории
Звучит логично. 
Сделал, теперь при загрузке страницы видно, что вначале появляются категории, а потом уже список блюд. Раньше они грузились и одновременно появлялись: https://github.com/MAVIKE/yad-flutter/pull/36/commits/9d0fa7cfe287dd7974f7e74c99a73dc4bbf9f38b

2021-05-07 19:12 UTC, vovac12 approved these changes

2021-05-07 19:15 UTC, vovac12 approved these changes

2021-05-07 20:09 UTC, merged